# ░█████╗░███████╗██╗░░░██╗███╗░░██╗██╗░██████╗░██╗░░░██╗███████╗████████╗░█████╗░████████╗███████╗███╗░░░███╗░██████╗
# ██╔══██╗██╔════╝██║░░░██║████╗░██║██║██╔═══██╗██║░░░██║██╔════╝╚══██╔══╝██╔══██╗╚══██╔══╝██╔════╝████╗░████║██╔════╝
# ███████║█████╗░░██║░░░██║██╔██╗██║██║██║██╗██║██║░░░██║█████╗░░░░░██║░░░██║░░██║░░░██║░░░█████╗░░██╔████╔██║╚█████╗░
# ██╔══██║██╔══╝░░██║░░░██║██║╚████║██║╚██████╔╝██║░░░██║██╔══╝░░░░░██║░░░██║░░██║░░░██║░░░██╔══╝░░██║╚██╔╝██║░╚═══██╗
# ██║░░██║██║░░░░░╚██████╔╝██║░╚███║██║░╚═██╔═╝░╚██████╔╝███████╗░░░██║░░░╚█████╔╝░░░██║░░░███████╗██║░╚═╝░██║██████╔╝
# ╚═╝░░╚═╝╚═╝░░░░░░╚═════╝░╚═╝░░╚══╝╚═╝░░░╚═╝░░░░╚═════╝░╚══════╝░░░╚═╝░░░░╚════╝░░░░╚═╝░░░╚══════╝╚═╝░░░░░╚═╝╚═════╝░
# Автор плагина: anton_flame (ТГК: https://t.me/anton_flame_coder)

totems:
  reusable_totem:
    display_name: "&aМногоразовый тотем"
    lore:
      - "&fДанный тотем можно использовать &a%uses% &fраз(а)"
    uses: 3
  effects_preserving_totem:
    display_name: "&dТотем, сохраняющий эффекты"
    lore:
      - "&fДанный тотем сохранит ваши эффекты после использования"
  auto_totem:
    display_name: "&cАвтототем"
    lore:
      - "&fДанный тотем активируется автоматически"

messages:
  no_permission: "&cНе хватает прав!"
  reloaded: "&aКонфигурация была перезагружена!"
  player_not_found: "&cИгрок не найден!"
  invalid_totem_type: "&cНеверный тип тотема!"
  invalid_amount: "&cНеверное количество!"
  totem_given: "&fТотем &6%type% x%amount% &fбыл выдан игроку &6%player%&f!"
  reusable_totem_used: "&fМногоразовый тотем был использован! Его еще можно использовать &a%uses% &fраз(а)"
  effects_preserving_totem_used: "&fТотем, сохраняющий эффекты был использован! Вы сохранили эффекты: &d%effects%"
  auto_totem_used: "&fАвтототем был использован!"
  help:
    - "&fПомощь по плагину:"
    - "&f- &6/afuniquetotems reload &f- перезагрузить конфигурацию"
    - "&f- &6/afuniquetotems give <игрок> <тотем> <количество> &f- выдать уникальный тотем игроку"